### ISSUE TITLE
Add version numbers

### ISSUE THREAD

**Issue by JoshuaWilsonBlack** [santiagobarreda/FastTrack#25]
Many thanks for this excellent tool!

It would be great to have named releases/version numbers in order to cite FastTrack.

I don't know how familiar you are with this side of github, but there's some documentation here: https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository

**Comment by santiagobarreda** [comment]
Thanks for the suggestion, however, the basic function hasn't really changed since the initial release and I have no plans to make changes to the way it works in the near future. I recently added a 'lite' version but it is the same algorithm with fewer saved files. I would like to clean the code up someday, but that's a different story. I guess I could name this version 1.0 and just leave it at that for the time being?
